# Generated by Django 4.0.4 on 2022-04-27 18:09

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enCours', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True)),
                ('objetreq', models.CharField(blank=True, max_length=200, null=True)),
                ('datereq', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsap', models.CharField(blank=True, max_length=50, null=True)),
                ('faceb', models.CharField(blank=True, max_length=150, null=True)),
                ('siteweb', models.URLField()),
                ('activite', models.CharField(blank=True, max_length=200, null=True)),
                ('besoin', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traduc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('formulaire', models.CharField(blank=True, max_length=250, null=True)),
                ('ordre', models.CharField(blank=True, max_length=250, null=True)),
                ('texte_fr', models.TextField(blank=True, null=True)),
                ('texte_eng', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
