# Generated by Django 4.0.4 on 2022-04-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mstart', '0002_alter_requete_siteweb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requete',
            new_name='ReqUser',
        ),
    ]
