# Generated by Django 4.0.4 on 2022-04-27 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=150, null=True)),
                ('dateBlog', models.DateField(auto_now_add=True, null=True)),
                ('contenu', models.TextField(null=True)),
                ('extrait', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(default='avatar.png', upload_to='Blog_Images')),
                ('dateExpire', models.DateField(blank=True, null=True)),
                ('auteur', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikesPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateLike', models.DateField(auto_now_add=True, null=True)),
                ('blogPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogpost', verbose_name='Post')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('dateComment', models.DateTimeField(auto_now_add=True, null=True)),
                ('blogPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogpost', verbose_name='Post')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
